name: release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The tag for this release (e.g., v1.2.3)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'

      - name: Setup ko
        uses: imjasonh/setup-ko@v0.8
        with:
          version: v0.9.3

      - name: Binary builds with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --tag ${{ inputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch container images
        env:
          VERSION_TAG: ${{ inputs.release_tag#v }}
        run: |
          set -euo pipefail
          tag="${{ inputs.release_tag }}"
          export KO_DOCKER_REPO="ghcr.io/${{ github.repository }}"
          export PATH="$(go env GOPATH)/bin:$PATH"
          echo "${{ secrets.GITHUB_TOKEN }}" | ko login ghcr.io --username ignored --password-stdin
          set -x
          ko publish --bare --tags "$tag" --platform=all .
